CREATE TABLE `crud_gc`.`data_mahasiswa` ( `id` INT(11) NOT NULL AUTO_INCREMENT ,
`nama_mahasiswa` VARCHAR(255) NULL ,  `NIM` INT(9) NULL , 
`jurusan` TEXT NULL , `program_studi` TEXT NULL ,  
`program_pendidikan` VARCHAR(3) NULL ,
`semester` INT(2) NULL , `indeks_prestasi` TEXT NULL , 
`status` TEXT NULL , `tempat_lahir` TEXT NULL , 
`jenis_kelamin` TEXT NULL , `agama` TEXT NULL , 
`nama_ayah` TEXT NULL , `nama_ibu` TEXT NULL , 
`NIK` INT(25) NULL , `tanggal_lahir` VARCHAR(100) NULL , 
`pendidikan` TEXT NULL , `pekerjaan` TEXT NULL , 
`nomor_telepon` INT(15) NULL , `nama_wali` TEXT NULL , 
`tanggal_lahir_wali` VARCHAR(100) NULL , `pendidikan_wali` TEXT NULL , 
`pekerjaan_wali` TEXT NULL , `nomor_telepon_wali` INT(15) NULL ,    
PRIMARY KEY  (`id`)) ENGINE = InnoDB;